mySite/Blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addEntryEditor/$', views.addEntryEditor, name='addEntryEditor'),
    url(r'^addEntry/$', views.addEntry, name='addEntry'),
    url(r'^editEntryEditor/(?P<blogEntry_pk>[0-9]+)/$', views.editEntryEditor, name='editEntryEditor'),
    url(r'^editEntry/(?P<blogEntry_pk>[0-9]+)/$', views.editEntry, name='editEntry'),
    url(r'^hideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.hideEntry, name='hideEntry'),
    url(r'^unhideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.unhideEntry, name='unhideEntry'),


    url(r'^adminPanel/$', views.adminPanel, name='adminPanel'),

]

mySite/MCEditor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^editor/$', views.editor, name='editor'),
    url(r'^example/$', views.example, name='example'),
]

mySite/MCUploader/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.list, name='list'),
    url(r'^delete/(?P<document_pk>[0-9]+)/$', views.delete, name='delete'),
    url(r'^upload/$', views.upload, name='upload'),
]

mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^MCEditor/', include('MCEditor.urls', namespace='MCEditor')),
    url(r'^LDSegmenter/', include('LDSegmenter.urls', namespace='LDSegmenter')),
    url(r'^Blog/', include('Blog.urls', namespace='Blog')),

    url(r'^MCUploader/', include('MCUploader.urls', namespace='MCUploader')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/MCEditor/models.py
from django.db import models

# Create your models here.

mySite/MCEditor/views.py
from django.shortcuts import render

def safe_text(text):
    text = text.replace("\r","")
    text = text.replace("\n","")
    text = text.replace('"',"'")
    text = text.replace("\\","\\\\")
    return text

# submit_url = url that the editor form submits to
# serialized_form_data = json-serialized data stored in "value" field of submission form
# header = title to display
# initial_text = intial text in the submission form
# editor.html itself submits a form with two POST variables:
#   form-text, the text of the form
#   serialized-form-data, a json serialized string
def editor(request,submit_url,serialized_form_data,header,initial_text):
    # Make sure we strip out all escape characters
    initial_text = safe_text(initial_text)
    context={'submit_url':submit_url, \
             'serialized_form_data':serialized_form_data, \
             'header':header, \
             'initial_text':initial_text, \
            }
    return render(request, 'MCEditor/editor.html', context)

# This is an example of how you might call the text editor
def example(request):
    html = editor(request,"/",{'a','b'},"Example editor form","initial text")
    return html

mySite/MCEditor/templates/MCEditor/editor.html
<!--
  Template variables:
    submit_url: This is the url that the editor should submit to
    form_data: This is serialized POST data that the editor should submit
    header: This is the "title"
    initial_text: Initial text shown in the editor
-->

{% extends "MCBase/base.html" %}

{% block javascript %}
  {% load staticfiles %}
  <script src="{% static 'MCEditor/js/ckeditor/ckeditor.js' %}"></script>
  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script> <!-- TODO: download this to static -->
{% endblock %}

{% block body_block %}

  <div id="post-editor-container" class="container height-100">
    <div id="post-editor-header">
      {{ header|safe }}
    </div>
    <a target="_blank" href="{% url 'MCUploader:list' %}">Click to upload file</a>

    <div>
      <form role="form" action="{{ submit_url }}" method=POST>

      <!-- POST data -->
      {% csrf_token %}
      <input type="hidden" name="serialized-form-data" value="{{ serialized_form_data }}" />

      <!-- WYSIWYG text editor -->
      <textarea cols="10" id="editor" name="form-text" rows="10" style="display:none;"></textarea>
      <script>
        CKEDITOR.replace( 'editor', {
          // Set height of editor window
          height: $("#post-editor-container").height() - $("#post-editor-header").height() - CKEDITOR.config.height - $("#submit-button").height() ,
        });
        // set initial text
        CKEDITOR.instances.editor.setData("{{ initial_text|safe }}")
      </script>

      <!-- submit button -->
      <button id="submit-button" type="submit" class="btn btn-primary">Submit your post!</button>
    </form>
  </div>
  </div>

{% endblock %}