mySite/Blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addEntryEditor/$', views.addEntryEditor, name='addEntryEditor'),
    url(r'^addEntry/$', views.addEntry, name='addEntry'),
    url(r'^editEntryEditor/(?P<blogEntry_pk>[0-9]+)/$', views.editEntryEditor, name='editEntryEditor'),
    url(r'^editEntry/(?P<blogEntry_pk>[0-9]+)/$', views.editEntry, name='editEntry'),
    url(r'^hideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.hideEntry, name='hideEntry'),
    url(r'^unhideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.unhideEntry, name='unhideEntry'),


    url(r'^adminPanel/$', views.adminPanel, name='adminPanel'),

]

mySite/myContent/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cv/$', views.cv, name='cv'),
    url(r'^publications/$', views.publications, name='publications'),
    url(r'^software/$', views.software, name='software'),
    url(r'^contact/$', views.contact, name='contact'),
]

mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^MCEditor/', include('MCEditor.urls', namespace='MCEditor')),
    url(r'^LDSegmenter/', include('LDSegmenter.urls', namespace='LDSegmenter')),
    url(r'^Blog/', include('Blog.urls', namespace='Blog')),

    url(r'^MCUploader/', include('MCUploader.urls', namespace='MCUploader')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/myContent/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context = {}
    #return render(request, 'myContent/index.html', context)
    return render(request, 'myContent/cv.html', context)

def cv(request):
    context = {}
    return render(request, 'myContent/cv.html', context)

def publications(request):
    context = {}
    return render(request, 'myContent/publications.html', context)

def software(request):
    context = {}
    return render(request, 'myContent/software.html', context)

def contact(request):
    context = {}
    return render(request, 'myContent/contact.html', context)

mySite/myContent/templates/myContent/contact.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'myContent/css/contact.css' %}">
{% endblock %}

{% block title %}
  contact
{% endblock %}

{% block body_block %}

  <div class="content">
    <div class="page-header">Contact me</div>

    <!-- bmc bioinformatics technique paper -->
    <div class="contact-text">
      <div class="contact-email">
        <b>michael</b> <i>dot</i> <b>chiang</b> <i>dot</i> <b>mc5</b> <i>at</i> <b>gmail</b> <i>dot</i> <b>com</b> <br />
      </div>
      Replace <i>dot</i> with "." and <i>at</i> with "@" (this is to prevent spam). <br />
      I check this email once a week.
    </div>



  </div>
{% endblock %}

mySite/myContent/templates/myContent/cv.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'myContent/css/cv.css' %}">
{% endblock %}

{% block title %}
  cv
{% endblock %}

{% block body_block %}
  <div class="content">


    <div class="page-header">About me</div>
    <!-- about me -->
    <div class="cv-text">
      <img src="{% static 'myContent/self_bw.jpg' %}" alt="me"><br/ >
      <br />
      My name is Michael.<br />
      I did my bachelor's in physics at Caltech.<br />
      I did my PhD in developmental biology at UCI.<br />
      One day, I will write blog entries about my work. For now, you
      can read my publications <a href="{% url 'myContent:publications' %}">here</a>.<br>
      I'm mostly a programmer; I worked on biological
      image processing during my PhD. <br />
    </div>


    <div class="page-header">Curriculum vitae</div>

    <!-- about me -->
    <h1>
      Download <a href="{% static 'myContent/CV.pdf' %}">here</a>.
    </h1>

{% endblock %}

mySite/myContent/templates/myContent/index.html
{% extends "MCBase/base.html" %}

{% block javascript %}
{% endblock %}

{% block title %}
  all about me
{% endblock %}

{% block body_block %}
  home
{% endblock %}

mySite/myContent/templates/myContent/publications.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'myContent/css/publications.css' %}">
{% endblock %}

{% block title %}
  publications
{% endblock %}

{% block body_block %}

<div class="content">
  <div class="page-header">Peer-reviewed publications (accepted)</div>
  <div>
    &nbsp; Click on "Explain Like I'm Five" for layman summaries of selected works. <br /><br />
  </div>

  <!-- bmc biology paper -->
  <div class="pub-title">
    Control of C. elegans germline stem cell cycling speed meets
    requirements of design to minimize mutation accumulation.
  </div>
  <div class="pub-source">
    <strong>Michael Chiang</strong>, Amanda Cinquin, Adrian Paz, Edward Meeds,
    Christopher A. Price, Max Welling, and Olivier Cinquin.
    <br />
    BMC Biology 2015; 13(1):51. DOI: 10.1186/s12915-015-0148-y.
  </div>
  <div class="pub-link">
    [<a href="{% static 'myContent/pubs/chiang-bmc_biol.pdf' %}">pdf</a>] &nbsp;
    [<a href="http://www.ncbi.nlm.nih.gov/pubmed/26187634">pubmed</a>] &nbsp;
    [<a href="{% url 'Blog:index' %}#e1">Explain Like I'm Five</a>] &nbsp;
  </div>

  <!-- bmc bioinformatics technique paper -->
  <div class="pub-title">
    Analysis of in vivo single cell behavior by high throughput,
    human-in-the-loop segmentation of three-dimensional images.
  </div>
  <div class="pub-source">
    <strong>Michael Chiang</strong>, Sam Hallman, Amanda Cinquin, Nabora Reyes de Mochel,
    Adrian Paz, Shimako Kawauchi, Anne L. Calof, Ken W. Cho, Charless C. Fowlkes
    and Olivier Cinquin.
    <br />
    BMC Bioinformatics 2015; 16:397. DOI: 10.1186/s12859-015-0814-7
  </div>
  <div class="pub-link">
    [<a href="{% static 'myContent/pubs/chiang-bmc_bioinformatics.pdf' %}">pdf</a>] &nbsp;
    [<a href="http://www.ncbi.nlm.nih.gov/pubmed/26607933/">pubmed</a>] &nbsp;
  </div>

  <!-- intermittent cycling paper -->
  <div class="pub-title">
    Intermittent stem cell cycling balances self-renewal and senescence of the C. elegans germ line
  </div>
  <div class="pub-source">
    Amanda Cinquin, <strong>Michael Chiang</strong>, Adrian Paz, Sam Hallman, Oliver Yuan,
    Indre Vysniauskaite, Charless Fowlkes and Olivier Cinquin.
    <br />
    PLOS Genetics 2016; 12(4):e1005985. DOI: 10.1371/journal.pgen.1005985
  </div>
  <div class="pub-link">
    [<a href="{% static 'myContent/pubs/cinquin-plos_genetics.pdf' %}">pdf</a>] &nbsp;
    [<a href="http://www.ncbi.nlm.nih.gov/pubmed/27077385/">pubmed</a>] &nbsp;
  </div>

  <!-- ted's bayesian inference paper -->
  <div class="pub-title">
    POPE: post optimization posterior evaluation of likelihood free models.
  </div>
  <div class="pub-source">
    Edward Meeds, <strong>Michael Chiang</strong>, Mary Lee, Olivier Cinquin,
    John Lowengrub and Max Welling.
    <br />
    BMC Bioinformatics 2015; 16:264. DOI: 10.1186/s12859-015-0658-1
  </div>
  <div class="pub-link">
    [<a href="{% static 'myContent/pubs/meeds-bmc_bioinformatics.pdf' %}">pdf</a>] &nbsp;
    [<a href="http://www.ncbi.nlm.nih.gov/pubmed/26289041/">pubmed</a>] &nbsp;
  </div>

  <!-- Soledad's paper -->
  <div class="pub-title">
    BMP signaling is required for cell cleavage in preimplantation-mouse embryos.
  </div>
  <div class="pub-source">
    Nabora Soledad Reyes de Mochel, Mui Luong, <strong>Michael Chiang</strong>,
    Anna L. Javier, Elizabeth Luu, Fujimori Toshihiko, Grant R. MacGregor,
    Olivier Cinquin and Ken W.Y. Cho.
    <br />
    Developmental Biology, 397(1), 45-55. DOI:10.1016/j.ydbio.2014.10.001
  </div>
  <div class="pub-link">
    [<a href="{% static 'myContent/pubs/mochel-dev_biol.pdf' %}">pdf</a>] &nbsp;
    [<a href="http://www.ncbi.nlm.nih.gov/pubmed/25446538/">pubmed</a>] &nbsp;
  </div>

  <!-- Amanda's diffusion paper -->
  <div class="pub-title">
    Semi-permeable diffusion barriers enhance patterning robustness in the C.
    elegans germ line.
  </div>
  <div class="pub-source">
    Amanda Cinquin, Likun Zheng, Pete H. Taylor, Adrian Paz, Lei Zhang,
    <strong>Michael Chiang</strong>, Joshua J. Snow, Qing Nie and Olivier Cinquin.
    <br />
    Developmental Cell, 35(4), 405-417. DOI: http://dx.doi.org/10.1016/j.devcel.2015.10.027
  </div>
  <div class="pub-link">
    [<a href="{% static 'myContent/pubs/cinquin-dev_cell.pdf' %}">pdf</a>] &nbsp;
    [<a href="http://www.ncbi.nlm.nih.gov/pubmed/26289041/">pubmed</a>] &nbsp;
  </div>

  <!-- Qing's addition to Soledad's paper -->
  <div class="pub-title">
     Gene Expression Noise Enhances Robust Organization of the Early 
     Mammalian Blastocyst
  </div>
  <div class="pub-source">
    William Holmes, Nabora Soledad Reyes de Mochel, Qixuan Wang, Huijing Du,
    Tao Peng, <strong>Michael Chiang</strong>, Olivier Cinquin, Ken Cho, 
    and Qing Nie.
    <br />
    PLOS Computational Biology, 13(1), e1005320. DOI: http://dx.doi.org/10.1371/journal.pcbi.1005320.
  </div>
  <div class="pub-link">
    [<a href="{% static 'myContent/pubs/holmes-plos_computational_biology.pdf' %}">pdf</a>] &nbsp;
    [<a href="http://www.ncbi.nlm.nih.gov/pubmed/28114387/">pubmed</a>] &nbsp;
  </div>

</div>
{% endblock %}

mySite/myContent/templates/myContent/software.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'myContent/css/software.css' %}">
{% endblock %}

{% block title %}
  software
{% endblock %}

{% block body_block %}
  <div class="content">
    <div class="page-header">Software portfolio</div>

    <!-- lipid droplet segmenter -->
    <div class="software-title">
      LDSegmenter (beta)
    </div>
    <div class="software-description">
      An ImageJ plugin for segmenting CARS images of macrophages. This plugin is
      currently in development.
    </div>
    <div class="software-link">
      [<a href="{% url 'LDSegmenter:index'  %}">link</a>]
    </div>

    <!-- journalClubDB -->
    <div class="software-title">
      journalClubDB (beta)
    </div>
    <div class="software-description">
      A website for collaborative discussion of scientific publications. This
      website is currently in development.
    </div>
    <div class="software-link">
      [<a href="http://www.journalClubDB.com">link</a>]
    </div>



  </div>
{% endblock %}