mySite/Blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addEntryEditor/$', views.addEntryEditor, name='addEntryEditor'),
    url(r'^addEntry/$', views.addEntry, name='addEntry'),
    url(r'^editEntryEditor/(?P<blogEntry_pk>[0-9]+)/$', views.editEntryEditor, name='editEntryEditor'),
    url(r'^editEntry/(?P<blogEntry_pk>[0-9]+)/$', views.editEntry, name='editEntry'),
    url(r'^hideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.hideEntry, name='hideEntry'),
    url(r'^unhideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.unhideEntry, name='unhideEntry'),


    url(r'^adminPanel/$', views.adminPanel, name='adminPanel'),

]

mySite/MCUploader/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.list, name='list'),
    url(r'^delete/(?P<document_pk>[0-9]+)/$', views.delete, name='delete'),
    url(r'^upload/$', views.upload, name='upload'),
]

mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^MCEditor/', include('MCEditor.urls', namespace='MCEditor')),
    url(r'^LDSegmenter/', include('LDSegmenter.urls', namespace='LDSegmenter')),
    url(r'^Blog/', include('Blog.urls', namespace='Blog')),

    url(r'^MCUploader/', include('MCUploader.urls', namespace='MCUploader')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/MCUploader/models.py
from django.db import models

class Document(models.Model):
    docfile = models.FileField(upload_to='')
    time = models.DateTimeField(auto_now_add=True)

mySite/MCUploader/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

mySite/MCUploader/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import redirect

from .models import Document
from .forms import DocumentForm

import os
from django.conf import settings

def upload(request):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    f = request.FILES['docfile']
    newdoc = Document(docfile = f)
    newdoc.save()
    return redirect(request.GET['next'])

def list(request):
    #root="/media/"
    #Path=settings.MEDIA_ROOT
    #os.chdir(Path)
    #for files in os.listdir("."):
    #    if files[-3:].lower() in ["gif","png","jpg","bmp"] :
    #        return HttpResponse(files)

    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    documents = Document.objects.all().order_by('-time')
    context = {'documents':documents}
    return render(request, 'MCUploader/list.html',context)


def delete(request,document_pk):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    doc = Document.objects.get(pk=document_pk)
    file_path=settings.MEDIA_ROOT
    os.remove(file_path+'/'+doc.docfile.name)
    doc.delete()
    return HttpResponseRedirect( reverse('MCUploader:list') )

mySite/MCUploader/templates/MCUploader/list.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <link rel="stylesheet" href="{% static 'MCUploader/css/list.css' %}">
{% endblock %}

{% block title %}
  Uploader
{% endblock %}



{% block body_block %}

  <!-- form to upload file -->
  {% include "MCUploader/uploadForm.html" %}
  <hr >

  <!-- display previously loaded files -->
  {% if documents %}
      <ul>
      {% for document in documents %}
          <li>
            {{ document.time }}
            &nbsp; &nbsp; &nbsp;
            <a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a>
            &nbsp; &nbsp; &nbsp;
            <a class="delete_link" href="{% url 'MCUploader:delete' document.pk %}">delete</a>
          </li>
      {% endfor %}
      </ul>
  {% else %}
      <p>No documents.</p>
  {% endif %}

{% endblock %}

mySite/MCUploader/templates/MCUploader/uploadForm.html
<!-- hidden form  -->
<form action="{% url 'MCUploader:upload' %}?next={{ request.path }}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <p>max. 42 megabytes</p>
  <p>
    <input id="id_docfile" name="docfile" type="file" />
  </p>
  <p>
    <input type="submit" value="Upload" />
  </p>
</form>