mySite/Blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addEntryEditor/$', views.addEntryEditor, name='addEntryEditor'),
    url(r'^addEntry/$', views.addEntry, name='addEntry'),
    url(r'^editEntryEditor/(?P<blogEntry_pk>[0-9]+)/$', views.editEntryEditor, name='editEntryEditor'),
    url(r'^editEntry/(?P<blogEntry_pk>[0-9]+)/$', views.editEntry, name='editEntry'),
    url(r'^hideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.hideEntry, name='hideEntry'),
    url(r'^unhideEntry/(?P<blogEntry_pk>[0-9]+)/$', views.unhideEntry, name='unhideEntry'),


    url(r'^adminPanel/$', views.adminPanel, name='adminPanel'),

]

mySite/mySite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')), # for description, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('myContent.urls', namespace='myContent')),
    url(r'^MCEditor/', include('MCEditor.urls', namespace='MCEditor')),
    url(r'^LDSegmenter/', include('LDSegmenter.urls', namespace='LDSegmenter')),
    url(r'^Blog/', include('Blog.urls', namespace='Blog')),

    url(r'^MCUploader/', include('MCUploader.urls', namespace='MCUploader')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # TODO: disable this in production


# -*- coding: utf-8 -*-
#from django.conf.urls import patterns, include, url
#from django.conf import settings
#from django.conf.urls.static import static

mySite/Blog/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogEntry(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    hidden = models.BooleanField(default=True)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.text

    def edit(self,text):
        self.text = text

mySite/Blog/views.py
from django.shortcuts import render
from MCEditor.views import editor
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import *

def index(request):
    blogEntries = BlogEntry.objects.filter(hidden=False)
    blogEntries = blogEntries.order_by('-time')
    context = {'blogEntries':blogEntries,}
    return render(request, 'Blog/index.html', context)

def adminPanel(request):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    blogEntries = BlogEntry.objects.all()
    blogEntries = blogEntries.order_by('-time')
    context = {'blogEntries':blogEntries,}
    return render(request, 'Blog/adminPanel.html', context)

def addEntryEditor(request):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    submit_url = reverse('Blog:addEntry')
    form_data = {}
    header = "Add a blog post"
    initial_text = ""
    html = editor(request,submit_url,form_data,header,initial_text) # See MCEditor.views
    return html
def addEntry(request):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    form_text = request.POST.get("form-text")
    blogEntry = BlogEntry(text=form_text)
    blogEntry.save()
    return HttpResponseRedirect( reverse('Blog:adminPanel') )

def editEntryEditor(request,blogEntry_pk):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    submit_url = reverse('Blog:editEntry',args=[blogEntry_pk])
    form_data = {}
    header = "Edit a blog post"
    initial_text = BlogEntry.objects.get(pk=blogEntry_pk).text
    html = editor(request,submit_url,form_data,header,initial_text) # See MCEditor.views
    return html
def editEntry(request,blogEntry_pk):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    form_text = request.POST.get("form-text")
    blogEntry = BlogEntry.objects.get(pk=blogEntry_pk)
    blogEntry.text = form_text
    blogEntry.save()
    return HttpResponseRedirect( reverse('Blog:adminPanel') )

def hideEntry(request,blogEntry_pk):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    blogEntry = BlogEntry.objects.get(pk=blogEntry_pk)
    blogEntry.hidden=True
    blogEntry.save()
    return HttpResponseRedirect( reverse('Blog:adminPanel') )
def unhideEntry(request,blogEntry_pk):
    if not request.user.is_superuser:
        return HttpResponse("You are not a superuser")
    blogEntry = BlogEntry.objects.get(pk=blogEntry_pk)
    blogEntry.hidden=False
    blogEntry.save()
    return HttpResponseRedirect( reverse('Blog:adminPanel') )

mySite/Blog/templates/Blog/adminPanel.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <script type="text/javascript" src="{% static 'Blog/js/index.js' %}"></script>
  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <link rel="stylesheet" href="{% static 'Blog/css/index.css' %}">
{% endblock %}

{% block title %}
  blog
{% endblock %}

{% block body_block %}
  <div class="content">
    <h1>admin panel</h1>

    <!-- admin interface -->
    <div>
      <a href="{% url 'Blog:addEntryEditor' %}">AddEntry</a>
    </div>

    <!-- all blog posts -->
    <div>
      {% if blogEntries %}
      {% for blogEntry in blogEntries %}
        <div class="blog-entry" id="e{{ blogEntry.pk }}">
          <div class="blog-date">
            <div>
              {{ blogEntry.time|date:'F j, Y' }}
            </div>
            <hr />
          </div>
          <div class="blog-text">
            {{ blogEntry|safe }}
          </div>

          <!-- admin panel -->
          {% if request.user.is_superuser %}
            <div>
              <a href="{% url 'Blog:editEntryEditor' blogEntry.pk %}">edit</a>
              {% if blogEntry.hidden %}
                <a href="{% url 'Blog:unhideEntry' blogEntry.pk %}">unhide</a>
              {% else %}
                <a href="{% url 'Blog:hideEntry' blogEntry.pk %}">hide</a>
              {% endif %}
            </div>
          {% endif %}

        </div>

      {% endfor %}
      {% else %}
        No blog entries
      {% endif %}
    </div>

  </div>
{% endblock %}

mySite/Blog/templates/Blog/index.html
{% extends "MCBase/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <script type="text/javascript" src="{% static 'Blog/js/index.js' %}"></script>
  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <link rel="stylesheet" href="{% static 'Blog/css/index.css' %}">
{% endblock %}

{% block title %}
  blog
{% endblock %}

{% block body_block %}
  <div class="content">

    <!-- admin interface -->
    {% if request.user.is_superuser %}
    <div><a href="{% url 'Blog:adminPanel' %}">adminPanel</a></div>
    {% endif %}

    <!-- all blog posts -->
    <div>
      {% if blogEntries %}
      {% for blogEntry in blogEntries %}
        <div class="blog-entry" id="e{{ blogEntry.pk }}">
          <div class="blog-date">
            <div>
              {{ blogEntry.time|date:'F j, Y' }}
            </div>
            <hr />
          </div>
          <div class="blog-text">
            {{ blogEntry|safe }}
          </div>



        </div>

      {% endfor %}
      {% else %}
        No blog entries
      {% endif %}
    </div>

  </div>
{% endblock %}